// code for the info panels on the side and across the track

import { PanelContent } from './data/panelContent.js';

export const panelData = [
  {
      id: "intro",
      position: [-1, 5, 10],
      rotation: [ 0, 0, 0],
      type: "text",
      contentId: "intro",
  },
  {
    id: "model1l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model1l",
  },
  {
    id: "model1r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model1r",
  },
  {
    id: "model2l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model2l",
  },
  {
    id: "model2r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model2r",
  },
  {
    id: "model3l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model3l",
  },
  {
    id: "model3r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model3r",
  },
  {
    id: "model4l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model4l",
  },
  {
    id: "model4r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "model4r",
  },
  {
    id: "chapter2",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "chapter2",
  },
  {
    id: "ch2p1l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch2p1l",
  },
  {
    id: "ch2p1r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch2p1r",
  },
  {
    id: "ch2p2l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch2p2l",
  },
  {
    id: "ch2p2r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch2p2r",
  },
  {
    id: "ch2p3l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch2p3l",
  },
  {
    id: "ch2p3r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch2p3r",
  },
  {
    id: "chapter3",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "chapter3",
  },
  {
    id: "ch3p1l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch3p1l",
  },
  {
    id: "ch3p1r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch3p1r",
  },
  {
    id: "ch3p2l",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch3p2l",
  },
  {
    id: "ch3p2r",
    position: [-10, 1, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "ch3p2r",
  },
  {
    id: "final",
    position: [0, 5, 10],
    rotation: [0, 0, 0],
    type: "text",
    contentId: "final",
  },
];